version: "3.9"
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim-server
    environment:
      - TZ=Europe/London
      - STEAM_UID=1026
      - STEAM_GID=1000
      - NAME=valheimserver
      - PORT=2456
      - WORLD=Dedicated
      - PASSWORD=daniel99
      - PUBLIC=1
    volumes:
      - /volume1/docker/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim:rw
      - /volume1/docker/valheim/server:/home/steam/valheim:rw
    network_mode: bridge
    restart: always
